### PR TITLE
feat: automatically generate postman collection from the openapi spec

### PR DESCRIPTION
**Pull request by rafaelcr**
## Description

This change adds the ability to generate a Postman collection from our OpenAPI spec using the [openapi-to-postman library](https://github.com/postmanlabs/openapi-to-postman). The resulting collection contains all of our endpoints including request and response examples.

Closes issue #746 and by extension #417 

## Type of Change
- [x] New feature
- [ ] Bug fix
- [x] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
No

## Are documentation updates required?
Yes. I will need to consult with @pgray-hiro to see where I should deposit this output file or if I should also add a Github action to generate the collection.

## Testing information
Run `npm run generate:postman` inside the `docs/` directory.

## Checklist
- [ ] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [x] `npm run test` passes
- [ ] Changelog is updated
- [x] Tag 1 of @kyranjamie or @zone117x for review

### CODE REVIEW

**Comment by rafaelcr** [comment]
@pgray-hiro the generated site (https://blockstack.github.io/stacks-blockchain-api/) currently has a button that says "Run in Postman" but I'd like to change that to a link to download the generated `collection.json`, what do you think?

**Review by kyranjamie — APPROVED** [review]
Awesome 👍🏼 

Would be great to set up the docs to work well with https://rest.sh/ too

**Review by zone117x — APPROVED** [review]
LGTM!

**Comment by pgray-hiro** [comment]
> @pgray-hiro the generated site (https://blockstack.github.io/stacks-blockchain-api/) currently has a button that says "Run in Postman" but I'd like to change that to a link to download the generated `collection.json`, what do you think?
> 
> I'm not sure if the gh-pages action uploads everything I place in the target directory or just `index.html` but I'll look into that.

@rafaelcr I think that's an appropriate modification. I'm actively working to replace the standalone built site with a [unified documentation site](https://docs.hiro.so/api), but it still builds in the same way as the current solution (i.e. Redoc). I suggest replacing the link in [line 19](https://github.com/blockstack/stacks-blockchain-api/blob/9a7165e3c9a2185684f77145f9d391991981cb82/docs/openapi.yaml#L19) of the spec yaml with the collection.json link.

**Review by pgray-hiro — APPROVED** [review]

**Comment by rafaelcr** [comment]
Done @pgray-hiro 👍 
Let me know if you run into any problems with this, though.

**Pull request merged**
