### PR TITLE
rosetta schema files and updated types

### PR DESCRIPTION
**Pull request by fariedt**
This PR contains the Rosetta API schema and entity files, and updated `index.d.ts` file.

### CODE REVIEW

**Comment by zone117x** [comment]
This looks good to me -- we only need to get the `stacks-blockchain-api / build-publish` action working for external PRs. That action tests the auto-generated client lib based off these schemas, and it can be obnoxiously picky with the OpenAPI spec. 

@CharlieC3 could you help here?

**Comment by CharlieC3** [comment]
@zone117x I just updated the workflow file in the master branch. Until this forked feature branch is rebased from master to pull down the updated workflow, the GH Actions will continue to fail.

@fariedt Can you rebase your branch off of our master branch to pull down the updated GH workflow file?

**Comment by zone117x** [comment]
@fariedt looks like there's a problem with the rebase on this PR as well. Once that is fixed, the CLA bot should be working properly.

**Comment by fariedt** [comment]
I pulled master into my fork, and then rebased my branch to it.  There was a conflict in `docs/index.d.ts` because of the commit for https://github.com/blockstack/stacks-blockchain-api/pull/196/commits/89165b2becc48b9e83f92f54564434fde291a403

I'm not sure how to resolve this.  Can you suggest a solution here?  I generally merge instead of rebasing, so this is new to me.

**Comment by zone117x** [comment]
Conflicts for generated files (like `docs/index.d.ts`) are easy to deal with -- just ignore the changes and re-run whatever script to generate latest. 
I don't think there should be any other conflicts, and a typical git rebase procedure should work.

**Comment by CharlieC3** [comment]
@fariedt No worries. I was able to fix this locally with your feature branch, here's what I did. (It would be a good idea to backup your local repo first).

1. Reset your feature branch to `0cc860b`, which was the last commit you made before the pull from `master.` 
```
git reset --hard 0cc860b
```
2. Then rebase from master like so, where `parent` points to the parent repo `blockstack/stacks-blockchain-api`:
```
git remote add parent git@github.com:blockstack/stacks-blockchain-api.git
git pull --rebase parent master
```

You'll need to resolve 2 conflicts in `docs/index.d.ts` during this.

3. After you edit `docs/index.d.ts` and the conflicts are resolved, run
```
git add docs/index.d.ts
git rebase --continue
```

Confirm all your changes are present in local repo before pushing up. Checking `git log` is also a good idea, you changes should appear _after_ any commits to `master`.
The git history should look like 
```
cad0e3a 2020-08-23 (HEAD -> feat/rosetta-schema-types) docs: remove title of metadata from network options request and network status request [fariedt]
375d060 2020-08-21 feat: add rosetta api schema for type information [fariedt]
84bd108 2020-08-24 (parent/master, origin/master, origin/HEAD, master) chore: npm audit fix [Matthew Little]
f00e6b2 2020-08-25 chore(release): 0.8.0 [skip ci] [semantic-release-bot]
25181fa 2020-08-24 chore: test fixes [Matthew Little]
c55c272 2020-08-24 chore: listing debug endpoints [Matthew Little]
08c6686 2020-08-24 chore: bump tx lib [Matthew Little]
db6d264 2020-08-20 fix: deserializing multisig txs [Matthew Little]
34ba78c 2020-08-20 fix: N-of-M multisig working [Matthew Little]
4cc155b 2020-08-20 fix: N-of-N (one to one) multisig txs working [Matthew Little]
d12ba53 2020-08-20 feat: initial debug endpoint support for sending multisig transactions [Matthew Little]
a466148 2020-08-24 chore(release): 0.7.0 [skip ci] [semantic-release-bot]
89165b2 2020-08-24 feat: expose target block time #192 [Matthew Little]
a3fdfe0 2020-08-24 chore: update gh workflow to work with fork PRs [CharlieC3]
c9c9127 2020-08-21 chore(release): fix gh workflow notifications [CharlieC3]
e16805e 2020-08-20 (tag: v0.6.0) chore(release): 0.6.0 [skip ci] [semantic-release-bot]
```

4. Then, force push up to your feature branch:
```
git push -f
```

**Comment by fariedt** [comment]
Thanks, it seems to have worked, at least for this feature branch.

**Pull request merged**
