### PR TITLE
Feat/bns/subdomains

### PR DESCRIPTION
**Pull request by noumanahmads**
## Description

1. Added subdomain support in the endpoint `/v1/names/{name}`
2. Schema files added for endpoints. Schema validation and success test cases are also added.
- `/v2/prices/namespaces/{tld}`
- `/v2/prices/names/{name}`
3. Implemented the TODO's which are pointed out in the previous PR's

For details refer to [issue](https://github.com/blockstack/stacks-blockchain-api/issues/317)

## Type of Change
- [x] New feature
- [x] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
No

## Testing information
Test cases are added for the endpoints implemented.
To run the test cases `npm run test:bns`

## Checklist
- [x] Code is commented where needed
- [x] Unit test coverage for new or modified code paths
- [x] `npm run test` passes
- [ ] Changelog is updated
- [ ] @zone117x for review

### CODE REVIEW

**Review by hstove — CHANGES_REQUESTED** [review]
I know this isn't from this PR, but I get a typescript error on line 52 of `import-v1/index.ts`, due to the `encoding` param. Can we change it to:

```ts
type Encodings =
  | 'ascii'
  | 'utf8'
  | 'utf-8'
  | 'utf16le'
  | 'ucs2'
  | 'ucs-2'
  | 'base64'
  | 'latin1'
  | 'binary'
  | 'hex';

// later in the `_write` function:
_write(chunk: any, encoding: Encodings, callback: (error?: Error | null) => void) {
`

**Comment by hstove** [comment]
This code has become quite a bit out of date with the master branch. For example, I'm seeing errors when broadcasting transactions through this code, because of errors in the proxy to the core node. There are a lot of changes to the RPC proxy code that have been shipped lately. We really should try and get this code and the `bns` branch back up to date.

**Comment by noumanahmads** [comment]
> I know this isn't from this PR, but I get a typescript error on line 52 of `import-v1/index.ts`, due to the `encoding` param. Can we change it to:
> 
> ```ts
> type Encodings =
>   | 'ascii'
>   | 'utf8'
>   | 'utf-8'
>   | 'utf16le'
>   | 'ucs2'
>   | 'ucs-2'
>   | 'base64'
>   | 'latin1'
>   | 'binary'
>   | 'hex';
> 
> // later in the `_write` function:
> _write(chunk: any, encoding: Encodings, callback: (error?: Error | null) => void) {
> `
> ```

Which typescript version you are using? 
Currently, I have `3.9.7`, and it is not showing any error.

**Comment by zone117x** [comment]
@hstove I'm not seeing any ts errors either. They should show up in CI. Are you using nvm and yarn (with yarn outside of nvm management)? I've seen similar issues from that.

**Comment by hstove** [comment]
Yeah, sorry, feel free to disregard the typescript error. I'm probably using a different node and/or typescript version in VSCode.

**Pull request merged**
