### PR TITLE
Rosetta construction/metadata  and construction/hash endpoints

### PR DESCRIPTION
**Pull request by noumanahmads**
Rosetta constuction/metadata endpoint implementation
Details [here](https://www.rosetta-api.org/docs/ConstructionApi.html#constructionmetadata)

- [ ] New feature implementation
- [ ] Unit test coverage

### CODE REVIEW

**Comment by zone117x** [comment]
This needs rebased onto latest master, then looks good to merge

**Comment by asimm241** [comment]
PR updated with rosetta construction/hash endpoint implementation
Details [here](https://www.rosetta-api.org/docs/ConstructionApi.html#constructionhash)

- [ ]  New feature implementation
- [ ]  Unit test coverage

**Comment by zone117x** [comment]
This does not appear to have been rebased properly and cannot be merged

**Comment by CharlieC3** [comment]
@noumanahmad001 It appears the `master` branch may have been pulled into your feature branch, rather than rebased underneath your commits. For example, we shouldn't see our release-bot adding commits to your branch.
Screen Shot 2020-09-22 at 4 46 58 PM

I tried cloning your branch and I think I found a way to try the rebase again using the following steps (You might want to test this on a duplicate branch first!):
1. On your branch, run `git reset --soft bd969d3` - this will restage the changes you've made since the `master` branch was pulled into this branch.
1. `git stash` - save those changes
1. `git reset --hard 8e0e067` - hard reset to the commit prior to pulling in the `master` branch.
1. `git remote add parent git@github.com:blockstack/stacks-blockchain-api.git` - Add the upstream parent repo as a remote entry
1. `git pull --rebase parent master` - Rebase from the `master` branch
1. `git stash pop` - Lay the changes you previously `stash`ed onto the current codebase.
1. Fix any conflicts, I had conflicts in 4 separate files.
1. `git add -A && git commit -m "<message>"` - Stage all files and commit to your feature branch.
1. `git push -f` - Force push the changes up to your remote feature branch.

**Comment by CharlieC3** [comment]
It looks like the `master` branch will pulled in again just as I left my previous comment, so we have 2 botched rebases now...Perhaps it would be simpler to recreate this branch with the changes at this point? :)

**Comment by asimm241** [comment]
@CharlieC3 did not see your comment before, I'll just delete this PR and recreate this branch with the same changes.

**Comment by CharlieC3** [comment]
No worries, we clicked submit at the same time! For future reference, you can perform a rebase like so:
`git pull --rebase <remote-name> <branch-name>`

It's very similar to a normal merge, just with a `--rebase` flag. The difference being a rebase will layer commits from `<branch-name>` underneath your commits whereas a normal `merge` will pull in updates from `<branch-name>` and layer them _on top_ of your commits.

**Comment by asimm241** [comment]
Gotcha!. Thanks, @CharlieC3.

**Comment by noumanahmads** [comment]
Closing this as @asimm241 has created new [pull request](https://github.com/blockstack/stacks-blockchain-api/pull/249)

**Comment by zone117x** [comment]
Thanks for the help @CharlieC3!

**Pull request closed without merging**
