### PR TITLE
Support reward address for stacking transactions

### LINKED ISSUE #672: [Rosetta][Construction-API][feature] pass in valid BTC address for constructing stacking transaction
the entire transaction construction flow:
`/preprocess` -> `/metadata` -> `/payloads` -> etc
needs to be able to handle passing in and using valid BTC address for constructing a stacking transaction to tell the it to send BTC rewards to that address for that stacking cycle.

This is so we can specify the BTC reward address to stack. Right now looking at `/payloads` it looks like the bitcoin address cannot be passed in and uses the BTC address that is converted from the key that made the STX address of the stacker.
https://github.com/blockstack/stacks-blockchain-api/blob/master/src/api/routes/rosetta/construction.ts#L582-L585

The stack-stx contract should be able to take in a specified BTC address: https://docs.stacks.co/references/stacking-contract#stack-stx

### PR DESCRIPTION
**Pull request by asimm241**
## Description
Support BTC reward(`pox_addr`) address  for `preprocess` and `payload`

closes #672 

## Type of Change
- [ ] New feature
- [x] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Checklist
- [x] Code is commented where needed
- [x] Unit test coverage for new or modified code paths
- [x] `npm run test` passes
- [ ] Changelog is updated
- [x] Tag 1 of @kyranjamie or @zone117x for review

### CODE REVIEW

**Review by zone117x — APPROVED** [review]
LGTM.
Seems like there should be some tests to verify the BTC address correctly ends up in the pox contract after submitting the stacking transaction, but that can be done in a later PR?

**Comment by asimm241** [comment]
@zone117x do we need to check if it is a valid btc address?

**Comment by asimm241** [comment]
> LGTM.
> Seems like there should be some tests to verify the BTC address correctly ends up in the pox contract after submitting the stacking transaction, but that can be done in a later PR?

You mean an integration test?

**Comment by zone117x** [comment]
> @zone117x do we need to check if it is a valid btc address?

It _looks_ like stacks.js `decodeBtcAddress` function used should be checking for a valid (and non-segwit) btc address. Please feel free to look into it and see if additional validation is needed.

> Do you mean an integration test? If yes, that can be done later.

Yep 👍

**Pull request merged**
