### PR TITLE
chore: add api architecture diagram

### LINKED ISSUE #776: Add API architecture overview
We should add this diagram to the following files:
- https://github.com/blockstack/stacks-blockchain-api/blob/master/overview.md (replace the ASCII diagram)
- https://github.com/blockstack/stacks-blockchain-api/blob/master/readme.md (add "architecture" chapter with diagram and link to the overview.md file)

APIArchitecture

### PR DESCRIPTION
**Pull request by rafaelcr**
## Description

This PR adds an API architecture diagram image to our README documentation.

Closes #776 

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [x] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
No

## Are documentation updates required?
No

## Testing information
N/A

## Checklist
- [ ] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [ ] `npm run test` passes
- [ ] Changelog is updated
- [x] Tag 1 of @kyranjamie or @zone117x for review

### CODE REVIEW

**Comment by kyranjamie** [comment]
Which tool is this made with? Whimsical? 🤔

**Review by agraebe — APPROVED** [review]

**Comment by agraebe** [comment]
> Which tool is this made with? Whimsical? 🤔

@eugeniadigon did it :)

**Comment by eugeniadigon** [comment]
> Which tool is this made with? Whimsical? 🤔

I made it on Figma

**Review by zone117x — APPROVED** [review]
Thanks @rafaelcr!

**Pull request merged**
