### PR TITLE
chore: add .nvmrc

### PR DESCRIPTION
**Pull request by marcosc90**
## Description

This PR adds `.nvmrc` for those who use `nvm` to quickly switch node versions between projects

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] API reference/documentation update
- [x] Other

## Does this introduce a breaking change?

No changes to production code.

## Testing information

run `nvm use` and node version should switch to `14.16.0`

### CODE REVIEW

**Review by zone117x — COMMENTED** [review]
I didn't know this existed! Super useful, thank you. 
Do you know how strict this is, and if it can be set to something like `v14.*` ?

**Comment by marcosc90** [comment]
> Do you know how strict this is, and if it can be set to something like `v14.*` ?

We can set it to `14` and should use the highest `14.x` that you have installed via NVM.

**Comment by zone117x** [comment]
Do you think we should use `v14` or `v14.16`?

**Comment by marcosc90** [comment]
I prefer a specific version unless we know for sure that it works on all 14.x.x.

**Comment by zone117x** [comment]
I think it would be safe to allow any patch version, unless nodejs breaks semver it should work?
Scoping it to a specific minor version makes the most sense to me. We should also update any dockerfiles like https://github.com/blockstack/stacks-blockchain-api/blob/b6fcf1fc6696d6ab97193018d0a619d0ca4e4a5b/Dockerfile#L1 to a more specific version as well.

**Comment by marcosc90** [comment]
> I think it would be safe to allow any patch version, unless nodejs breaks semver it should work?

Agree, we can set `v14.16`, so any `v14.16.z` would work

**Comment by zone117x** [comment]
Can you update with `v14.16` and then this looks good to merge 👍

**Review by zone117x — APPROVED** [review]
LGTM, thanks @marcosc90!

**Pull request merged**
