### PR TITLE
Pin exact dependencies

### PR DESCRIPTION
**Pull request by MHassanTariq**
## Description

This PR updates the dependencies and uses exact ones. Required dependencies have been updated for the proper working of the project. 

For details refer to issue #975 

## Type of Change
- [ ] New feature
- [X] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Checklist
- [ ] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [ ] `npm run test` passes
- [ ] Changelog is updated
- [ ] Tag 1 of @rafaelcr or @zone117x for review

### CODE REVIEW

**Review by rafaelcr — APPROVED** [review]
LGTM

**Review by zone117x — CHANGES_REQUESTED** [review]
The package-lock.json file is showing this change downgrading many dependencies to older versions. If a dependency is included with `^1.0.0`, then typically its highest semver compatible version will be used, e.g. `1.5.0`.

So simply removing the `^` char from package.json is going to result in version downgrades.

**Comment by MHassanTariq** [comment]
I'll do that for all libraries. I did it only for the ones that would otherwise break the project. 
Thanks for pointing it out!

**Review by zone117x — APPROVED** [review]
LGTM, thanks @MHassanTariq!

**Pull request merged**
