### PR TITLE
Remove regtest reference from openapi.yaml

### PR DESCRIPTION
**Pull request by MHassanTariq**
## Description

This PR removes references for regtest from openapi.yaml.

For details refer to issue #784 

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [x] API reference/documentation update
- [ ] Other

## Are documentation updates required?
- [x] Link to documentation updates: [openapi.yaml](https://github.com/blockstack/stacks-blockchain-api/blob/develop/docs/openapi.yaml#L7-L8)

## Checklist
- [ ] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [ ] `npm run test` passes
- [ ] Changelog is updated
- [x] Tag 1 of @kyranjamie or @zone117x for review

### CODE REVIEW

**Comment by MHassanTariq** [comment]
I understood from issue #784 that [thesel](https://github.com/blockstack/stacks-blockchain-api/blob/develop/docs/openapi.yaml#L7-L8) references were to be removed from the openapi.yaml. @agraebe let me know, if I misunderstood the issue, or if there is something more than this.

**Review by agraebe — APPROVED** [review]
thanks, LGTM!

**Comment by agraebe** [comment]
@MHassanTariq I'm seeing only an update in the yaml file - should the docs and client be impacted by this change?

**Review by kyranjamie — APPROVED** [review]

**Comment by MHassanTariq** [comment]
@agraebe none that I know of. It was a documentation change. However, let me know if you want me to remove the `regtest` entirely from our code as well.
cc: @zone117x @asimm241

**Review by zone117x — APPROVED** [review]

**Pull request merged**
